# theme = "onedark"
theme = "mytheme"


[editor]
line-number = "relative"
completion-trigger-len = 1
color-modes = true
idle-timeout = 0
bufferline = "multiple"

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right =  ["diagnostics", "selections", "total-line-numbers", "file-encoding", "file-type"]
mode.normal = "Normal"
mode.insert = "Insert"
mode.select = "Select"

[editor.lsp]
display-messages = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[editor.indent-guides]
render = true
