[character]
success_symbol = "[❱](bold red)[❱](bold yellow)[❱](bold green)"
error_symbol = "[✘](bold red)"
vicmd_symbol = "[❰](bold green)[❰](bold yellow)[❰](bold red)"

[cmd_duration]
min_time = 1_000
show_milliseconds = true
style = "bold red"
show_notifications = true
min_time_to_notify = 300

[directory]
style = "bold green"

[git_branch]
format = "[$symbol$branch]($style) "
truncation_length = 10

[git_commit]
disabled = true

[git_metrics]
disabled = false

[line_break]
disabled = true

[package]
disabled = true
