#!/bin/sh
sh $HOME/.screenlayout/monitor.sh
screen -dmS nitrogen nitrogen --restore
screen -dmS picom picom
screen -dmS dunst dunst
screen -dmS kde kdeconnect-indicator &
screen -dmS discord discord --start-minimized
screen -dmS eww eww daemon
eww open-many bar-left bar-middle bar-right
setxkbmap colemakdh
redshift -b 1.0:0.7 -l 43.5:-79.7 -t 6500:6500 &
noisetorch -i
sleep 0.1
nitrogen --random ~/bg
emacs --daemon &
